spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  application:
    name: chat-service

logging:
  level:
    com.connectcrew.teamone: trace

server:
  port: 8086
