spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  profiles:
    include: oauth


jwt:
  secret: b82e3ae4-539d-43c4-b695-f5a7f0bddb30 # 임의의 Secret Key

app:
  user: http://localhost:8085
  project: http://localhost:8084
  chat: http://localhost:8086

logging:
  level:
    com.connectcrew.teamone: trace

resource:
  base-path: /path/to/resource

server:
  port: 9081