server:
  port: 8080

app:
  user: http://user:8080
  project: http://project:8080
  chat: http://chat:8080

spring:
  kafka:
    bootstrap-servers: kafka:9093

resource:
  base-path: /resources/banner