spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  application:
    name: user-service

  kafka:
    bootstrap-servers: 192.168.0.56:9082

server:
  port: 8085

db:
  host: Mysql Host 주소
  port: 3306
  id: Mysql ID
  pw: Mysql Password
  database: user

logging:
  level:
    com.connectcrew.teamone: trace

discord:
  bot:
    token: Discord Bot Token

  channel:
    report: Discord Report Channel ID
    error: Discord Error Channel ID