spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  application:
    name: user-service

server:
  port: 8085

db:
  host: Mysql Host 주소
  port: 3306
  id: Mysql ID
  pw: Mysql Password
  database: user